const StudyPlan = require("../models/StudyPlan");
const StudyGoal = require("../models/StudyGoal");
const { generateStudyPlan, adaptStudyPlan} = require("../services/aiService");


const createPlan = async (req, res) => {
  try {
    const { goalId, date, tasks } = req.body;

    if (!goalId || !date || !tasks || tasks.length === 0) {
      return res.status(400).json({
        success: false,
        message: "Goal ID, date and tasks are required",
      });
    }

    // Make sure the goal belongs to the logged-in user
    const goal = await StudyGoal.findOne({
      _id: goalId,
      userId: req.userId,
    });

    if (!goal) {
      return res.status(404).json({
        success: false,
        message: "Study goal not found",
      });
    }

    const plan = await StudyPlan.create({
      userId: req.userId,
      goalId,
      date,
      tasks,
    });

    res.status(201).json({
      success: true,
      message: "Study plan created successfully",
      plan,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};


const getTodayPlan = async (req, res) => {
  try {
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);

    const endOfDay = new Date();
    endOfDay.setHours(23, 59, 59, 999);

    const plan = await StudyPlan.findOne({
      userId: req.userId,
      date: {
        $gte: startOfDay,
        $lte: endOfDay,
      },
    }).populate("goalId");

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: "No study plan found for today",
      });
    }

    res.status(200).json({
      success: true,
      plan,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};


const completeTask = async (req, res) => {
  try {
    const { taskId } = req.params;

    const plan = await StudyPlan.findOne({
      userId: req.userId,
      "tasks._id": taskId,
    });

    if (!plan) {
      return res.status(404).json({
        success: false,
        message: "Task not found",
      });
    }

    const task = plan.tasks.id(taskId);

    task.completed = true;

    await plan.save();

    res.status(200).json({
      success: true,
      message: "Task completed successfully",
      task,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

const generatePlan = async (req, res) => {
  try {
    const { goalId } = req.body;

    // 1. Validate goalId
    if (!goalId) {
      return res.status(400).json({
        success: false,
        message: "Goal ID is required",
      });
    }

    // 2. Find goal and check ownership
    const goal = await StudyGoal.findOne({
      _id: goalId,
      userId: req.userId,
    });

    if (!goal) {
      return res.status(404).json({
        success: false,
        message: "Study goal not found",
      });
    }

    // 3. Generate plan using Gemini
    const aiPlan = await generateStudyPlan(goal);

    // 4. Validate AI response
    if (!aiPlan.schedule || !Array.isArray(aiPlan.schedule) || aiPlan.schedule.length !== 7) {
      return res.status(500).json({
        success: false,
        message: "Invalid study plan generated by AI",
      });
    }

    // 5. Generate StudyPlan documents
    const plans = [];

    const startDate = new Date();
    startDate.setHours(0, 0, 0, 0);

    for (const dayPlan of aiPlan.schedule) {
      const planDate = new Date(startDate);

      planDate.setDate(
        startDate.getDate() + (dayPlan.day - 1)
      );

      // Validate daily study time
      const totalMinutes = dayPlan.tasks.reduce(
        (total, task) => total + task.duration,
        0
      );

      const expectedMinutes = goal.dailyStudyHours * 60;

      if (totalMinutes !== expectedMinutes) {
        return res.status(500).json({
          success: false,
          message: `AI generated invalid duration for day ${dayPlan.day}`,
        });
      }

      const plan = await StudyPlan.findOneAndUpdate(
        {
          userId: req.userId,
          date: planDate,
        },
        {
          userId: req.userId,
          goalId: goal._id,
          date: planDate,
          tasks: dayPlan.tasks,
          version: 1,
        },
        {
          new: true,
          upsert: true,
          runValidators: true,
        }
      );

      plans.push(plan);
    }

    res.status(201).json({
      success: true,
      message: "Study plan generated successfully",
      plans,
    });
  } catch (error) {
    console.error("Generate Plan Error:", error);

    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};


const getWeeklyPlans = async (req, res) => {
  try {
    const today = new Date();

    const startDate = new Date(today);
    startDate.setHours(0, 0, 0, 0);

    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + 6);
    endDate.setHours(23, 59, 59, 999);

    const plans = await StudyPlan.find({
      userId: req.userId,
      date: {
        $gte: startDate,
        $lte: endDate,
      },
    })
      .sort({ date: 1 })
      .populate("goalId", "title deadline");

    res.status(200).json({
      success: true,
      startDate,
      endDate,
      plans,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

const adaptivePlan = async (req, res) => {
  try {
    const {
      goalId,
      topic,
      score,
      totalQuestions,
    } = req.body;

    // 1. Validate input
    if (
      !goalId ||
      !topic ||
      score === undefined ||
      !totalQuestions
    ) {
      return res.status(400).json({
        success: false,
        message:
          "goalId, topic, score and totalQuestions are required",
      });
    }

    // 2. Validate score
    if (
      score < 0 ||
      score > totalQuestions
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid score",
      });
    }

    // 3. Find goal and check ownership
    const goal = await StudyGoal.findOne({
      _id: goalId,
      userId: req.userId,
    });

    if (!goal) {
      return res.status(404).json({
        success: false,
        message: "Study goal not found",
      });
    }

    // 4. Check topic exists in syllabus
    let topicExists = false;

    for (const subject of goal.subjects) {
      const foundTopic = subject.topics.find(
        (item) => item.name === topic
      );

      if (foundTopic) {
        topicExists = true;
        break;
      }
    }

    if (!topicExists) {
      return res.status(400).json({
        success: false,
        message:
          "Topic does not exist in this goal's syllabus",
      });
    }

    // 5. Calculate percentage
    const percentage =
      (score / totalQuestions) * 100;

    // 6. Only adapt if topic is weak
    if (percentage >= 50) {
      return res.status(200).json({
        success: true,
        message:
          "Performance is acceptable. No adaptive changes required.",
        topic,
        score,
        totalQuestions,
        percentage,
        weak: false,
        weakAreas: goal.weakAreas,
      });
    }

    // 7. Add topic to weak areas
    if (!goal.weakAreas.includes(topic)) {
      goal.weakAreas.push(topic);
      await goal.save();
    }

    // 8. Get future plans
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const futurePlans = await StudyPlan.find({
      userId: req.userId,
      goalId: goalId,
      date: {
        $gt: today,
      },
    }).sort({ date: 1 });

    if (futurePlans.length === 0) {
      return res.status(404).json({
        success: false,
        message: "No future study plans found",
      });
    }

    // 9. Ask Gemini to adapt the plans
    const aiResult = await adaptStudyPlan(
      goal,
      topic,
      futurePlans
    );

    // 10. Validate AI response
    if (
      !aiResult.plans ||
      !Array.isArray(aiResult.plans)
    ) {
      return res.status(500).json({
        success: false,
        message:
          "AI returned invalid adaptive plan",
      });
    }

    // 11. Update future plans
    const updatedPlans = [];

    for (const aiPlan of aiResult.plans) {
      const plan = futurePlans.find((item) => {
        const dbDate = new Date(item.date)
          .toISOString()
          .split("T")[0];

        return dbDate === aiPlan.date;
      });

      if (!plan) {
        continue;
      }

      const totalMinutes = aiPlan.tasks.reduce(
        (total, task) =>
          total + task.duration,
        0
      );

      const expectedMinutes =
        goal.dailyStudyHours * 60;

      // Make sure AI respects daily hours
      if (totalMinutes !== expectedMinutes) {
        return res.status(500).json({
          success: false,
          message:
            `AI generated invalid duration for ${aiPlan.date}`,
        });
      }

      plan.tasks = aiPlan.tasks;

      await plan.save();

      updatedPlans.push(plan);
    }

    res.status(200).json({
      success: true,
      message:
        "Study plan adapted successfully using AI",
      topic,
      score,
      totalQuestions,
      percentage,
      weak: true,
      weakAreas: goal.weakAreas,
      updatedPlans,
    });
  } catch (error) {
    console.error("Adaptive Plan Error:", error);

    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

module.exports = {
  createPlan,
  getTodayPlan,
  completeTask,
  generatePlan,
  getWeeklyPlans,
  adaptivePlan,
};
